CREATE TABLE f_bde_dept (
dept_no VARCHAR(50),
nom VARCHAR(50),
pop VARCHAR(50)
)
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
DEFAULT DIRECTORY sources
ACCESS PARAMETERS

(
RECORDS DELIMITED BY newline
CHARACTERSET UTF8
BADFILE nf26p011_logs:'import.bad'
LOGFILE nf26p011_logs:'import.log'
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
)
LOCATION ('departements.csv'))
REJECT LIMIT UNLIMITED;

SELECT count(*) from f_bde_dept;