
CREATE TABLE f_bde_marketing (
dept VARCHAR(50),
magasin VARCHAR(50),
rayonnage VARCHAR(50),
bestseller VARCHAR(50),
recent VARCHAR(50)
)
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
DEFAULT DIRECTORY sources
ACCESS PARAMETERS
(
RECORDS DELIMITED BY newline
SKIP 1
CHARACTERSET UTF8
BADFILE nf26p011_logs:'import.bad'
LOGFILE nf26p011_logs:'import.log'
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
)
LOCATION ('marketing.csv'))
REJECT LIMIT UNLIMITED;

SELECT count(*) from f_bde_marketing;


CREATE TABLE f_bde_dept (
dept_no VARCHAR(50),
nom VARCHAR(50),
pop VARCHAR(50)
)
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
DEFAULT DIRECTORY sources
ACCESS PARAMETERS

(
RECORDS DELIMITED BY newline
CHARACTERSET UTF8
BADFILE nf26p011_logs:'import.bad'
LOGFILE nf26p011_logs:'import.log'
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
)
LOCATION ('departements.csv'))
REJECT LIMIT UNLIMITED;

SELECT count(*) from f_bde_dept;



CREATE TABLE f_bde_ventes (
ticket VARCHAR(50),
tdate VARCHAR(50),
isbn VARCHAR(50),
mag VARCHAR(50)
)
ORGANIZATION EXTERNAL
(TYPE ORACLE_LOADER
DEFAULT DIRECTORY nf26_data
ACCESS PARAMETERS
(
RECORDS DELIMITED BY newline
CHARACTERSET UTF8
BADFILE nf26p011_logs:'import.bad'
LOGFILE nf26p011_logs:'import.log'
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
)
LOCATION ('Fantastic'))
REJECT LIMIT UNLIMITED;

SELECT count(*) from f_bde_ventes;


DROP VIEW f_bde_catalogue IF EXISTS;
CREATE VIEW f_bde_catalogue AS
SELECT *
FROM NF26.catalogue;

CREATE OR REPLACE VIEW  f_bde_catalogue AS
SELECT * from nf26.catalogue;